name: Fetch Decorations Details

on:
  workflow_run:
    workflows: ["Update Decorations List"]
    types:
      - completed

jobs:
  fetch-decorations-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq for JSON processing
      run: sudo apt-get install jq

    - name: Read decorations list and fetch details
      run: |
        echo "[]" > decorations.json
        for id in $(cat decorations_list.json | jq -r '.[]'); do
          curl -s https://api.guildwars2.com/v2/homestead/decorations/$id | jq '.' >> decorations.json
        done

    - name: Commit and push updated decorations.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add decorations.json
        git commit -m "Update decorations.json with detailed data"
        git push
