name: Update and Fetch Decorations and Categories

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows for manual trigger of the workflow

jobs:
  update-and-fetch-decorations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl for JSON processing
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch Decorations List and Details
        run: |
          # Fetch the list of decoration IDs
          curl -s https://api.guildwars2.com/v2/homestead/decorations -o decorations_list.json

          # Initialize an empty array to store the results
          echo "[]" > decorations.json

          # Split the list into chunks of 200 IDs and fetch details
          ids=$(jq -r '.[]' decorations_list.json)
          chunk_size=200
          for chunk in $(echo "$ids" | xargs -n $chunk_size | sed 's/ /,/g'); do
            curl -s "https://api.guildwars2.com/v2/homestead/decorations?ids=$chunk" | \
            jq -s 'add' >> temp.json
          done

          # Combine all the chunks into a single JSON array
          jq -s 'add' temp.json > decorations.json
          rm temp.json
          rm decorations_list.json

      - name: Fetch Decoration Categories
        run: |
          # Fetch the list of decoration category IDs
          curl -s https://api.guildwars2.com/v2/homestead/decorations/categories -o decoration_categories_list.json

          # Initialize an empty array to store the results
          echo "[]" > decoration_categories.json

          # Split the list into chunks of 200 IDs and fetch details
          category_ids=$(jq -r '.[]' decoration_categories_list.json)
          chunk_size=200
          for chunk in $(echo "$category_ids" | xargs -n $chunk_size | sed 's/ /,/g'); do
            curl -s "https://api.guildwars2.com/v2/homestead/decorations/categories?ids=$chunk" | \
            jq -s 'add' >> temp_categories.json
          done

          # Combine all the chunks into a single JSON array
          jq -s 'add' temp_categories.json > decoration_categories.json
          rm temp_categories.json
          rm decoration_categories_list.json

      - name: Fetch and Update Decorations with Image Data
        run: |
          # Iterate over each decoration and fetch additional image data
          jq -c '.[]' decorations.json | while read decoration; do
            # Extract the decoration name and ID
            name=$(echo "$decoration" | jq -r '.name')
            id=$(echo "$decoration" | jq -r '.id')

            # URL encode the decoration name for API requests
            encodedName=$(echo "$name" | jq -Rr @uri)
            titles="${encodedName}%20(Handiwork)|${encodedName}%20Decoration|${encodedName}"
            apiUrl="https://wiki.guildwars2.com/api.php?action=query&titles=${titles}&prop=pageimages&piprop=original|thumbnail&format=json&origin=*"

            # Debugging: Fetch and display the raw response
            echo "Fetching data for: $name"
            imageResponse=$(curl -s "$apiUrl")
            echo "Raw response: $imageResponse" # Debug: Check raw response

            # Validate JSON response format before using jq
            if ! echo "$imageResponse" | jq empty; then
              echo "Invalid JSON response for decoration: $name" # Debug: Log invalid response
              continue # Skip this decoration if the response is invalid
            fi

            # Extract image information safely
            # Fetch the pages and ensure the selection handles missing values gracefully
            page=$(echo "$imageResponse" | jq -c '.query.pages[] | select(.original != null) | select(.title | contains("Handiwork")) // select(.title | contains("Decoration")) // .')

            # If image data is found, add it to the decoration object
            if [ -n "$page" ]; then
              originalUrl=$(echo "$page" | jq -r '.original.source // empty')
              thumbnailUrl=$(echo "$page" | jq -r '.thumbnail.source // empty')

              # Update the decoration JSON object with image URLs if available
              if [ -n "$originalUrl" ]; then
                decoration=$(echo "$decoration" | jq --arg original "$originalUrl" --arg thumbnail "$thumbnailUrl" '. + {original: $original, thumbnail: $thumbnail}')
              fi
            else
              echo "No matching image data found for: $name"
            fi

            # Append the updated decoration back to the JSON array
            echo "$decoration" >> updated_decorations.json
          done

          # Combine updated decorations into a single JSON array
          jq -s '.' updated_decorations.json > decorations.json
          rm updated_decorations.json

      - name: Commit and push updated decorations and categories
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add decorations.json decoration_categories.json
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update decorations.json and decoration_categories.json with detailed data"
            git push
          fi