name: Update and Fetch Decorations and Categories

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows for manual trigger of the workflow

jobs:
  update-and-fetch-decorations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl for JSON processing
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch Decorations List and Details
        run: |
          # Fetch the list of decoration IDs
          curl -s https://api.guildwars2.com/v2/homestead/decorations -o decorations_list.json

          # Initialize an empty array to store the results
          echo "[]" > decorations.json

          # Split the list into chunks of 200 IDs and fetch details
          ids=$(jq -r '.[]' decorations_list.json)
          chunk_size=200
          for chunk in $(echo "$ids" | xargs -n $chunk_size | sed 's/ /,/g'); do
            curl -s "https://api.guildwars2.com/v2/homestead/decorations?ids=$chunk" | \
            jq -s 'add' >> temp.json
          done

          # Combine all the chunks into a single JSON array
          jq -s 'add' temp.json > decorations.json
          rm temp.json
          rm decorations_list.json

      - name: Fetch Decoration Categories
        run: |
          # Fetch the list of decoration category IDs
          curl -s https://api.guildwars2.com/v2/homestead/decorations/categories -o decoration_categories_list.json

          # Initialize an empty array to store the results
          echo "[]" > decoration_categories.json

          # Split the list into chunks of 200 IDs and fetch details
          category_ids=$(jq -r '.[]' decoration_categories_list.json)
          chunk_size=200
          for chunk in $(echo "$category_ids" | xargs -n $chunk_size | sed 's/ /,/g'); do
            curl -s "https://api.guildwars2.com/v2/homestead/decorations/categories?ids=$chunk" | \
            jq -s 'add' >> temp_categories.json
          done

          # Combine all the chunks into a single JSON array
          jq -s 'add' temp_categories.json > decoration_categories.json
          rm temp_categories.json
          rm decoration_categories_list.json

      - name: Fetch and Update Decorations with Image Data
        run: |
          # Iterate over each decoration and fetch additional image data
          jq -c '.[]' decorations.json | while read decoration; do
            # Debug: Print the full decoration object at the start of each loop
            echo "Processing decoration: $decoration"

            # Extract the description field and sanitize it if necessary
            description=$(echo "$decoration" | jq -r '.description' | sed 's/"/\\"/g')

            # Rebuild the JSON object with the sanitized description field
            decoration=$(echo "$decoration" | jq --arg description "$description" '.description = $description')

            # Debug: Print the sanitized decoration object
            echo "Sanitized decoration: $decoration"

            # Extract the decoration name and ID
            name=$(echo "$decoration" | jq -r '.name')
            id=$(echo "$decoration" | jq -r '.id')

            # URL encode the decoration name for API requests
            encodedName=$(echo "$name" | jq -Rr @uri)
            titles="${encodedName}%20(Handiwork)|${encodedName}%20Decoration|${encodedName}"
            apiUrl="https://wiki.guildwars2.com/api.php?action=query&titles=${titles}&prop=pageimages&piprop=original|thumbnail&format=json&origin=*"

            # Fetch the primary image data
            echo "Fetching data for: $name"
            imageResponse=$(curl -s "$apiUrl")
            echo "Raw response: $imageResponse" # Debug: Check raw response

            # Validate that the raw response is valid JSON
            if ! echo "$imageResponse" | jq empty; then
              echo "Invalid JSON response for decoration: $name"
              continue # Skip this decoration if the response is invalid
            fi

            # Extract and prioritize the page based on titles
            page=$(echo "$imageResponse" | jq -c '.query.pages | to_entries[] | select(.value.original != null) | .value' | jq 'select(.title | contains("Handiwork")) // select(.title | contains("Decoration")) // .')

            # Check if valid page data is found
            if [ -n "$page" ]; then
              # Extract the image URLs
              originalUrl=$(echo "$page" | jq -r '.original.source // empty')
              thumbnailUrl=$(echo "$page" | jq -r '.thumbnail.source // empty')

              # Update the decoration object with URLs if found
              if [ -n "$originalUrl" ]; then
                decoration=$(echo "$decoration" | jq --arg original "$originalUrl" --arg thumbnail "$thumbnailUrl" '. + {original: $original, thumbnail: $thumbnail}')
                echo "Updated decoration with images: $name"
              else
                echo "No valid original URL found for: $name"
              fi
            else
              echo "No matching page with valid image data found for: $name"

              # Fallback: Fetch RDF data if no valid image found
              rdfTitle=$(echo "$name" | sed 's/ /_/g')
              rdfApiUrl="https://corsproxy.io/?$(echo "https://wiki.guildwars2.com/index.php?title=Special:ExportRDF/$rdfTitle" | jq -Rr @uri)"

              rdfResponse=$(curl -s "$rdfApiUrl")
              if [ -n "$rdfResponse" ]; then
                # Extract appearance details from RDF data
                fullFilename=$(echo "$rdfResponse" | grep -oP 'rdf:resource="[^"]*"' | grep 'Has_appearance' | sed -e 's/rdf:resource="//' -e 's/"//')

                if [ -n "$fullFilename" ]; then
                  # Extract file title and create fallback URL
                  filenameTitle=$(basename "$fullFilename" | sed 's/-3A/:/g')
                  fallbackApiUrl="https://wiki.guildwars2.com/api.php?action=query&titles=$(echo "$filenameTitle" | jq -Rr @uri)&prop=pageimages&piprop=original|thumbnail&format=json&origin=*"

                  fallbackResponse=$(curl -s "$fallbackApiUrl")
                  fallbackPage=$(echo "$fallbackResponse" | jq '.query.pages | to_entries[] | select(.value.original != null) | .value')
                  fallbackOriginal=$(echo "$fallbackPage" | jq -r '.original.source // empty')
                  fallbackThumbnail=$(echo "$fallbackPage" | jq -r '.thumbnail.source // empty')

                  # Update decoration with fallback data
                  if [ -n "$fallbackOriginal" ]; then
                    decoration=$(echo "$decoration" | jq --arg original "$fallbackOriginal" --arg thumbnail "$fallbackThumbnail" '. + {original: $original, thumbnail: $thumbnail}')
                    echo "Updated decoration with fallback images: $name"
                  else
                    echo "No original image found using RDF fallback for: $name"
                  fi
                else
                  echo "No valid RDF resource found for: $name"
                fi
              else
                echo "Error fetching RDF data for: $name"
              fi
            fi

            # Append the updated decoration back to the JSON array
            echo "$decoration" >> updated_decorations.json
          done

          # Combine updated decorations into a single JSON array
          jq -s '.' updated_decorations.json > decorations.json
          rm updated_decorations.json

      - name: Commit and push updated decorations and categories
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add decorations.json decoration_categories.json
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update decorations.json and decoration_categories.json with detailed data"
            git push
          fi