name: Update Decorations

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, at the top of the hour
  workflow_dispatch: # Allows for manual trigger of the workflow

jobs:
  update-decorations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch current decorations data
      run: curl -s https://api.guildwars2.com/v2/homestead/decorations -o new_decorations.json

    - name: Compare and update decorations.json
      id: check_changes
      run: |
        if ! cmp -s new_decorations.json decorations.json; then
          mv new_decorations.json decorations.json
          echo "Decorations file has changed."
          echo "file_changed=true" >> $GITHUB_ENV
        else
          echo "No changes detected."
          echo "file_changed=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.file_changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add decorations.json
        git commit -m "Update decorations.json with new data"
        git push
